.github/workflows/publish.yaml, CONTRIBUTING.md, pyproject.toml
Adding in the proper GH action file to handle both 
- pypi releases (test and prod)
- GH releases (draft and real)
The test path should get triggered on PRs to main; the others will only get triggered if we add a tag.
=> testing pypi release test

.github/workflows/main.yaml, .github/workflows/publish.yaml, CONTRIBUTING.md
* Changed to trigger releases manually on the github web UI
*  parses Ruff's version directly
* uses UV as a python package installer
=> Updated github workflows to do manual triggers from web UI for both test and prod

.github/pull_request_template.md, .github/workflows/docs.yaml, docs/source/conf.py
[Closing this PR](https://github.com/mozilla-ai/lm-buddy/pull/44) in favor of a new cleaner workflow rebased off latest `main`. This PR adds a workflow for building docs and rebuilding the documentation site on merge into `main`.  It runs on every opened branch as a separate workflow and takes ~`30` seconds to build/deploy. 
Check the `yaml` config trigger a manual run.
=> Adding Actions workflow to build Sphinx docs

.github/workflows/docs.yaml, .github/workflows/main.yaml, .github/workflows/publish.yaml
=> Update env var name for Poetry PyPI token

examples/configs/finetuning/finetuning_config.yaml, pyproject.toml
Noticed `epochs` was an invalid value when running training.
=> Fix up epoch vs epochs in config

.github/workflows/docs.yaml, .github/workflows/merge_checks.yaml, CONTRIBUTING.md, pyproject.toml
We'd like to pin lm-harness to the hash resolving trust_remote_code (see issue here:https://github.com/mozilla-ai/lm-buddy/issues/49), and also updating to include wandb for logging
=> Pinning lm-harness at the git hash

pyproject.toml
We wanted to pin lm-eval to a git hash to encompass the latest changes, but PyPI doesn't allow to publish packages with git-hash pinned dependencies, so reverting for now so we can update the PyPI version with the latest Ray on publish. 
See errors here: https://github.com/mozilla-ai/lm-buddy/actions/runs/8238935806/job/22531036074
=> Bumping the library version and pinning lm-eval-harness to a PyPI Distribution

CONTRIBUTING.md, docs/source/index.rst
We learned that we can't publish git-hash pinned dependencies, so adding that for the publishing section and cleaning up some docs formatting.
=> Add PyPI docs

examples/configs/prometheus/prometheus_config.yaml, pyproject.toml, src/lm_buddy/cli/run.py, src/lm_buddy/cli/schema.py, src/lm_buddy/integrations/vllm.py, src/lm_buddy/integrations/wandb/artifact_utils.py, src/lm_buddy/jobs/__init__.py, src/lm_buddy/jobs/_entrypoints/__init__.py, src/lm_buddy/jobs/_entrypoints/prometheus.py, src/lm_buddy/jobs/configs/__init__.py, src/lm_buddy/jobs/configs/prometheus.py
Here's the first version of the lm-buddy prometheus entrypoint!
I tried to keep the script relatively close to the original evaluation script, as I'd like to use it as a use case for a "conversion" of some existing tool (a tutorial is being written...)
I feel it still needs some massaging as I am not 100% sure of the implementation choices I took (format of configs, using one method or another to get artifacts, etc). Happy to receive some early feedback and iterate on it soon!
=> Added v0 of prometheus lm-buddy entrypoint

pyproject.toml, src/lm_buddy/jobs/_entrypoints/lm_harness.py
LM-eval has [now been bumped](https://github.com/EleutherAI/lm-evaluation-harness/releases/tag/v0.4.2) to `0.4.2`, incorporating `trust_remote_code`=`True` as a default for a select set of curated datasets, removing the warning for those datasets specifically. Also bumping `datasets` as a result. 
In the change, we also remove the need to call `lm_eval.tasks.initialize_tasks()`
```python
import lm_eval
task_manager = TaskManager() # pass include_path="/path/to/my/custom/tasks" if desired
lm_eval.simple_evaluate(model=lm, tasks=["arc_easy"], task_manager=task_manager)
```
Run a test Ray job using the evaluate entrypoint to evaluate using some default params:
```yaml
model:
load_from: "tiiuae/falcon-7b"
torch_dtype: "bfloat16"
evaluator (note this is still using the old API):
tasks: …
```
=> Update lm-eval version and API

.github/workflows/docs.yaml, .github/workflows/merge_checks.yaml, CONTRIBUTING.md, pyproject.toml
We can use UV again now that we don't use git-hash specified dependencies. See issue: https://github.com/mozilla-ai/lm-buddy/issues/79
=> Reinstate uv for tests

pyproject.toml, src/lm_buddy/jobs/asset_loader.py, src/lm_buddy/jobs/evaluation/lm_harness.py, src/lm_buddy/jobs/evaluation/prometheus.py, src/lm_buddy/jobs/evaluation/ragas.py, src/lm_buddy/jobs/finetuning.py, src/lm_buddy/paths.py, tests/unit/jobs/test_asset_loader.py
- Added S3 support for datasets
- Refactored the asset loaders to (1) support S3 datasets and (2) be asset-specific. We now have one class for datasets, one for models/configs, one for tokenizers.
- Used pytest for backwards compatibility.
- Manually tested S3 dataset loading in the prometheus job (we might want to rely on localstack for testing)
=> Added S3 support for datasets, refactored asset loaders

examples/configs/evaluation/hf_evaluate_config.yaml, examples/configs/evaluation/hf_evaluate_inference_server_config.yaml, examples/configs/evaluation/hf_evaluate_openai_config.yaml, pyproject.toml, src/lm_buddy/buddy.py, src/lm_buddy/cli/evaluate.py, src/lm_buddy/configs/jobs/__init__.py, src/lm_buddy/configs/jobs/hf_evaluate.py, src/lm_buddy/configs/vllm.py, src/lm_buddy/jobs/asset_loader.py, src/lm_buddy/jobs/evaluation/hf_evaluate.py, src/lm_buddy/jobs/evaluation/metrics.py, src/lm_buddy/jobs/model_clients.py, src/lm_buddy/jobs/utils.py, src/lm_buddy/paths.py
Added a new `evaluate huggingface` entrypoint which supports evaluation of local and remote models (seq2seq, causal, openai, vllm, llamafile) and loading datasets / saving results on s3.
```
lm-buddy evaluate huggingface --config examples/configs/evaluation/hf_evaluate_config.yaml
```
https://mzai.atlassian.net/browse/MZPLATFORM-78
I know we discussed messaging to mzai-platform's backend directly from lm-buddy jobs.
I am 100% in favor of it, I just wanted to keep this PR independent from messaging and I will create a new one to be tested together with the updated mzai-platform code.
=> New huggingface eval for the summarization use case with rouge, meteor, and bertscore

pyproject.toml
=> Added evaluate with latest version and bumped lm-buddy version

pyproject.toml, src/lm_buddy/jobs/evaluation/conversation.py, src/lm_buddy/jobs/evaluation/prometheus.py
Removed the dependency on fastchat, which fixes a lockfile generation down the line due to a chain of imports ending in a library (wavedrom) with bad metadata / setup file.
For now I just imported one single script from an older version of the library, then we'll get rid of it for good as prometheus only needs llama-2 conversation template
- `lm-buddy evaluate prometheus --config <a valid config file>` (more details in https://asciinema.org/a/FiYe21Ld7vRv7ouwcVtIRIdB8) - tested locally and working
- `pytest`
=> Updated prometheus job to get rid of fschat dependency

pyproject.toml, tests/integration/test_lm_harness.py
As discussed, this changes the dependency structure of this repo to make all packages that require Torch optional by default. This allows reuse of the configs more readily without other structural changes.
Tested internally by generating lockfiles on a project requiring this project with different  combos of [torchy, test, docs], verified pytorch is only in the ones in `torchy`.
=> Makes deps that require torch optional by default

pyproject.toml
fixing this here for now; it's causing some annoyances elsewhere.
=> pins transitive dep of numpy version to <2

pyproject.toml, src/lm_buddy/jobs/asset_loader.py, src/lm_buddy/jobs/evaluation/hf_evaluate.py, src/lm_buddy/jobs/model_clients.py, src/lm_buddy/paths.py
Three main commits:
- added `allow_remote_code` to config => allows us to run Phi models
- fixed `max_samples` bug (now if the value is 0 all samples are considered, if it is larger than len(dataset) we get a warning and all the dataset is used)
- added support for Mistral API (created a general `APIModelClient` class and made OAI and Mistral as two subclasses as so much code was in common)
- bonus: added model name in output evals file :-)
Tested manually with different configs (seq2seq models locally, OAI, Mistral) and with pytest.
=> Mixed fixes + support for Mistral API

pyproject.toml, src/lm_buddy/configs/huggingface.py, src/lm_buddy/jobs/asset_loader.py, src/lm_buddy/jobs/evaluation/hf_evaluate.py, src/lm_buddy/jobs/model_clients.py
Since 4.40.0, transformers does not get model_max_tokens from the model's family dict but explicitly looks for this parameter in `tokenizer_config.json`. Not all models provide this, so one possibility is to explicitly allow users to provide this parameter in the config. This PR implements exactly this.
Tested with facebook/bart-large-cnn + pytest unit/integration tests.
=> Added model_max_length as a tok parameter

.github/workflows/merge_checks.yaml, .pre-commit-config.yaml, CONTRIBUTING.md, pyproject.toml, src/lm_buddy/configs/huggingface.py, src/lm_buddy/configs/jobs/lm_harness.py, src/lm_buddy/jobs/evaluation/hf_evaluate.py, src/lm_buddy/jobs/evaluation/lm_harness.py, tests/integration/test_lm_harness.py
I updated pyproject.toml to use more recent libs. The main reason was transformers so we could run more recent models but I ran a general update using `pip-review` to get latest versions. These are the steps I followed:
- used pip-review to update all libs
- check there were no inconsistencies
- test lm-buddy with the new set of libs
- updated `pyproject.toml` by picking the updated versions from the output of `pip freeze`
- re-installed everything in a new env and made sure there were no inconsistencies
- tested lm-buddy again
The tests I ran were unit/integration tests + manually running lm-buddy for summarization eval (currently our main job).
Interestingly, `tests/integration/test_lm_harness.py::test_lm_harness_job` passes when I test locally
=> Fixes flakey integration test/syncs deps

pyproject.toml
We're pinning wandb and datasets due to regressions from upper-bound versions because integration tests were failing with updated versions. 
Run `pytest -s tests/integration/test_finetuning.py` locally
=> Hard pin datasets and wandb

README.md, pyproject.toml
Commit 0975fb2 changes the CLI groups `finetune` and `evaluate`, but the Ray job submission example in the README file still uses the deprecated `run` command.
Update the example to match the new API.
Run the example script on a Ray cluster.
=> Update Ray job submission example in README

README.md
lm-buddy is [being folded into Lumigator](https://github.com/mozilla-ai/lumigator/pull/209). We'd like to make sure people understand the change before we archive the repo.
=> Notice of archive of repo 
